APP_NAME = "HordaRPG"
APP_VERSION = "0.1.0"

DEFAULT_LANGUAGE = "pt-BR"
DEFAULT_THEME = "dark"

CONFIG_FILE_NAME = "config.json"
LOG_FILE_NAME = "app.log"

GRID_FILE_EXTENSION = ".grid"
CHARACTER_FILE_EXTENSION = ".char"
BOOK_FILE_EXTENSION = ".book"

MAX_GRID_SIZE = 1000
MIN_GRID_SIZE = 5